  (setq send-mail-function (quote smtpmail-send-it))
  (setq smtpmail-smtp-server "smtp.163.com")
  (setq smtpmail-smtp-service 25)
  (setq user-full-name "StoneEpigraph")
  (setq user-mail-address "stoneepigraph@163.com")
